import { Page } from '@playwright/test'

export async function interceptionResponseAddress(page: Page) {
  await page.route('Request URL: https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address', async (route) => {
    const response = await page.request.fetch(route.request())
    const mockResponseObject = {
      suggestions: [
        {
          value: 'г Владивосток, ул Басаргина, д 20А, кв 6',
          unrestricted_value: '690080, Приморский край, г Владивосток, Первомайский р-н, ул Басаргина, д 20А, кв 6',
          data: {
            postal_code: '690080',
            country: 'Россия',
            country_iso_code: 'RU',
            federal_district: 'Дальневосточный',
            region_fias_id: '43909681-d6e1-432d-b61f-ddac393cb5da',
            region_kladr_id: '2500000000000',
            region_iso_code: 'RU-PRI',
            region_with_type: 'Приморский край',
            region_type: 'край',
            region_type_full: 'край',
            region: 'Приморский',
            area_fias_id: null,
            area_kladr_id: null,
            area_with_type: null,
            area_type: null,
            area_type_full: null,
            area: null,
            city_fias_id: '7b6de6a5-86d0-4735-b11a-499081111af8',
            city_kladr_id: '2500000100000',
            city_with_type: 'г Владивосток',
            city_type: 'г',
            city_type_full: 'город',
            city: 'Владивосток',
            city_area: null,
            city_district_fias_id: null,
            city_district_kladr_id: null,
            city_district_with_type: 'Первомайский р-н',
            city_district_type: 'р-н',
            city_district_type_full: 'район',
            city_district: 'Первомайский',
            settlement_fias_id: null,
            settlement_kladr_id: null,
            settlement_with_type: null,
            settlement_type: null,
            settlement_type_full: null,
            settlement: null,
            street_fias_id: '84385027-b740-4816-89c1-52d94c0c9572',
            street_kladr_id: '25000001000003300',
            street_with_type: 'ул Басаргина',
            street_type: 'ул',
            street_type_full: 'улица',
            street: 'Басаргина',
            stead_fias_id: null,
            stead_cadnum: null,
            stead_type: null,
            stead_type_full: null,
            stead: null,
            house_fias_id: 'f43450fc-8325-4362-968d-704224d3bce3',
            house_kladr_id: '2500000100000330010',
            house_cadnum: null,
            house_type: 'д',
            house_type_full: 'дом',
            house: '20А',
            block_type: null,
            block_type_full: null,
            block: null,
            entrance: null,
            floor: null,
            flat_fias_id: 'f41605e0-9371-44cc-a1ca-27433fc5c423',
            flat_cadnum: '25:28:000000:9381',
            flat_type: 'кв',
            flat_type_full: 'квартира',
            flat: '6',
            flat_area: '77.2',
            square_meter_price: '296153',
            flat_price: '22863012',
            postal_box: null,
            fias_id: 'f41605e0-9371-44cc-a1ca-27433fc5c423',
            fias_code: null,
            fias_level: '9',
            fias_actuality_state: '0',
            kladr_id: '2500000100000330010',
            geoname_id: '2013348',
            capital_marker: '2',
            okato: '05401367000',
            oktmo: '05701000001',
            tax_office: '2540',
            tax_office_legal: '2540',
            timezone: 'UTC+10',
            geo_lat: '43.07553',
            geo_lon: '131.95708',
            beltway_hit: null,
            beltway_distance: null,
            metro: null,
            divisions: null,
            qc_geo: '0',
            qc_complete: null,
            qc_house: null,
            history_values: null,
            unparsed_parts: null,
            source: null,
            qc: null,
          },
        },
      ],
    }
    route.fulfill({
      response,
      body: JSON.stringify(mockResponseObject),
    })
  })
}
